### ISSUE TITLE
libbioscience-types not found

### ISSUE THREAD

**Issue by ngeiswei** [singnet/agi-bio#5]
After installing agi-bio I get the following error when loading the bioscience module
```scheme
scheme@(guile-user)> (use-modules (opencog bioscience))
;;; compiling /usr/share/guile/site/2.2/opencog/bioscience.scm
;;; compiled /home/nilg/.cache/guile/ccache/2.2-LE-8-3.A/usr/share/guile/site/2.2/opencog/bioscience.scm.go
While compiling expression:
In procedure dynamic-link: file: "libbioscience-types", message: "file not found"
```

If I add the absolute path of `"libbioscience-types" in https://github.com/singnet/agi-bio/blob/c68bab5b6a2d724cedc5045aed70a9c2df91bb24/bioscience/bioscience.scm#L10 to get
```scheme
(load-extension "/usr/local/lib/opencog/libbioscience-types" "bioscience_types_init")
```
It works, but maybe there's a better way...

**Comment by Habush** [comment]
Have you tried adding `/usr/local/lib/opencog` to `LD_LIBRARY_PATH`? That works for me.

**Comment by ngeiswei** [comment]
Yes, it works, I'm really surprised I need to do that, it's supposed to be already somewhere in my system, I would have thought.

**Comment by ngeiswei** [comment]
Another option is to run
```bash
sudo ldconfig /usr/local/lib/opencog
```

**Comment by ngeiswei** [comment]
I guess I can close, thanks.

**Comment by Habush** [comment]
Can you add `SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)` to the cmake file see if it fixes the issue without the need to manually set `LD_LIBRARY_PATH`?

**Comment by ngeiswei** [comment]
Adding `SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)` to cmake config doesn't work.
